### ISSUE TITLE
`wasm-pack` build log appears with `watch: true` but not `watch: false`

### ISSUE THREAD

**Issue by trevyn** [emily-curry/snowpack-plugin-wasm-pack#2]
Thanks also for picking up this useful plugin. :)

I noticed that the Rust / `wasm-pack` build log shows up with `watch: true` but not `watch: false`. The latter is clearly the better-behaved option, but those logs are mighty handy; do you think it would be possible to get them to appear in both modes?

**Comment by emily-curry** [comment]
Hey there! Happy to hear you find this useful (or at the very least, fun).  
I totally agree, and I've made this change in #4. Would you mind checking out release 1.1.3 and seeing if it has the behaviors you expect?

**Comment by trevyn** [comment]
Awesome! Yes, 1.1.3 has the desired behavior.

I noticed that it doesn't seem to include the helpful invocation line that watch does, e.g.

`[Running 'wasm-pack --log-level warn build --target web --out-dir frontend/src/turbocharger_generated --out-name index --dev']`

But that's just a minor thing.

**Comment by emily-curry** [comment]
I've included those invocation args in 1.1.4! It was a small change.
